POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createAccount(name: \"RestClientAccount\", email: \"restclient@example.com\", password: \"qweBR!123\") { _id name email balance created_at updated_at } }"
}
