POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { account (_id: \"66bb6ad39755ad5858542880\") { _id name email password balance created_at updated_at transactions { _id amount description created_at } } }"
}
