POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ account(id: \"default-account-id\") { id owner_name balance created_at updated_at transactions { id amount description date } } }"
}
